### ISSUE TITLE
Maps disappear after a while

### ISSUE THREAD

**Issue by Knoedel** [tyrantelf/gmod-mapvote#15]
After the server changes the recently played map will disappear in future mapvotes even though the cooldown is disabled. 

Root of the problem may be that even though cooldown is disabled in the config the addon creates the file recentmaps.txt which lists the recently played maps and disables them for future votes. 

The problem can be solved if you delete the recentmaps.txt in the garrysmod/data/mapvote folder. Could you look into the problem?

**Comment by Zverina** [comment]
I actually disabled the cooldown but it still works properly for me. If we get lucky, the current map gets put up on the list to be played again. Though, the map sometimes does take ages to appear. 

Random is random, I suppose.

**Comment by tyrantelf** [comment]
This problem seems to come up at random times...  Delete the content of recentmaps.txt and make the file read-only as a work around until I get time to fix it.
