### ISSUE TITLE
[Suggestion] Add ability to use mapcycle

### ISSUE THREAD

**Issue by Lykrast** [tyrantelf/gmod-mapvote#24]
It would be great to have an option to use the mapcycle file instead of making a list using a bunch of prefixes, this would allow easier management if someone wants to quickly change the map list or to have a different map rotation for different setups or to simply easily whitelist certain maps without having to remove them (like for example some css maps).

**Comment by dkalaxdk** [comment]
Or add a "Whitelist" for maps. Where you can write up a list of the maps you want in rotation.
