### ISSUE TITLE
Maps not shown

### ISSUE THREAD

**Issue by Simsari** [tyrantelf/gmod-mapvote#9]
Hi mapvote-users and creators,

my problem is, that I added two new maps to my server (there were 6 before) with the prefixes "cs_" and "de_", but they don't show up in the mapvote list at the end of the round...

This is my config: {"RTVPlayerCount":1,"MapLimit":24,"TimeLimit":15,"AllowCurrentMap":true,"MapPrefixes":{"1":"ttt_","2":"cs_","3":"de_"},"MapsBeforeRevote":0,"EnableCooldown":false}

I added the two new maps like every map before and didn't made anything special. :-(

The maplimit is 24 and there are 8 maps on the server.

Please help
Thank you for every single answer
Sincerely
Simsari

**Comment by Diehard08** [comment]
The links dont work bro. Btw how did you set it up for zs?
